### ISSUE TITLE
Deprecation message

### ISSUE THREAD

**Issue by artivis** [iosifache/semgrep-snap#4]
Running the semgrep snap results in the following deprecation message:

`Using 'python -m semgrep' to run Semgrep is deprecated as of 1.38.0. Please simply run 'semgrep' instead.`

**Comment by iosifache** [comment]
Hey Jeremie,

The command that the snap was using [was deprecated in `1.38.0`](https://github.com/semgrep/semgrep/blob/develop/CHANGELOG.md#1381---2023-09-01). I've updated the Semgrep command and released a new version.

Thanks!
